formatting:
   MaximumLineLength:
      active: false
      maxLineLength: 120
   NoWildcardImports:
      active: false

style:
   MaxLineLength:
      active: false
      maxLineLength: 120
      excludePackageStatements: true
      excludeImportStatements: true
      excludeCommentStatements: false
   WildcardImport:
      active: false
      excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
      excludeImports: ['java.util.*', 'kotlinx.android.synthetic.*']
