formatting:
   MaximumLineLength:
      active: false
      maxLineLength: 120
   NoWildcardImports:
      active: false

style:
   MaxLineLength:
      active: false
      maxLineLength: 120
      excludePackageStatements: true
      excludeImportStatements: true
      excludeCommentStatements: false
   WildcardImport:
      active: false
      excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
      excludeImports: ['java.util.*', 'kotlinx.android.synthetic.*']

naming:
   TopLevelPropertyNaming:
      active: true
      excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
      constantPattern: '[A-Za-z][_A-Z0-9]*'
      propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
      privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'
