name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
env:
  BASEIMAGE: "cgr.dev/chainguard/jre:openjdk-jre-17"
  IMAGE_BASENAME: ghcr.io/${{ github.repository }}
jobs:
  build:
    name: Build all the things
    runs-on: ubuntu-20.04
    permissions:
       contents: read
       packages: write
       id-token: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # ratchet:actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
      - uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6 # ratchet:gradle/wrapper-validation-action@v1
      - name: Build and test the app
        run: ./gradlew clean test shadowJar
      - name: Install cosign
        uses: sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: "v2.0.0"
      - name: Verify distroless base image
        run: cosign verify --certificate-identity "https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main"  --certificate-oidc-issuer "https://token.actions.githubusercontent.com" $BASEIMAGE
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # ratchet:docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Docker image tag with short sha
        id: dockertag
        run: echo "img_tag=$(git rev-parse --short HEAD)" >> ${GITHUB_OUTPUT}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # ratchet:docker/setup-buildx-action@v2
      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # ratchet:docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: ${{ env.IMAGE_BASENAME }}:${{ steps.dockertag.outputs.img_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -  name: Install cosign
         uses: sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65 # ratchet:sigstore/cosign-installer@main
         with:
            cosign-release: 'v2.0.0'
      -  name: Sign the container image
         run: cosign sign --yes ${{ env.IMAGE_BASENAME }}@${{ steps.build-push.outputs.digest }}
      -  name: Create SBOM
         run: ./gradlew cyclonedxBom
      -  name: Sign the container image
         run: cosign sign --yes ${{ env.IMAGE_BASENAME }}@${{ steps.build-push.outputs.digest }}
      -  name: Attest image
         run: cosign attest --yes --predicate build/reports/bom.json --type cyclonedx ${{ env.IMAGE_BASENAME }}@${{ steps.build-push.outputs.digest }}
    outputs:
      tag: "${{ steps.dockertag.outputs.img_tag }}"

  deploy_to_prod:
    name: Deploy to prod-gcp
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: nais/deploy/actions/deploy@fdd2da585ae15831342aad18847dbcc4213f72fb # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml,.nais/alerts.yaml
          VARS: .nais/prod.yaml
          IMAGE: ${{ env.IMAGE_BASENAME }}:${{ needs.build.outputs.tag }}


