name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "build.provenance"
      - "**/slsa.yaml"
jobs:
  build:
    name: Build all the things
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # ratchet:actions/checkout@v2
      - uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf # ratchet:actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b # ratchet:gradle/wrapper-validation-action@v1
      - name: Build and test the app
        run: sudo ./gradlew clean test shadowJar
      - name: Install cosign
        uses: sigstore/cosign-installer@3d3d32a83e307c72740f6095be918624b57e65fa # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.8.0'
      - name: Verify distroless base image
        run: cosign verify --key distroless.pub gcr.io/distroless/java17
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # ratchet:docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Docker image tag with short sha
        id: dockertag
        run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"
      - name: Build and push the Docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # ratchet:docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.dockertag.outputs.docker_img }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy_to_dev:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # ratchet:actions/checkout@v2
      - name: Generate Docker image tag
        id: dockertag
        run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"
      - uses: nais/deploy@727f0adc1e2ba8ef9286f42230ade61a70d2da05 # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/dev.yaml
          IMAGE: ${{ steps.dockertag.outputs.docker_img }}
  deploy_to_prod:
    name: Deploy to prod-gcp
    needs: deploy_to_dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # ratchet:actions/checkout@v2
      - name: Generate Docker image tag
        id: dockertag
        run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"
      - uses: nais/deploy@727f0adc1e2ba8ef9286f42230ade61a70d2da05 # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/prod.yaml
          IMAGE: ${{ steps.dockertag.outputs.docker_img }}
