name: main

on:
   push:
      branches:
         - main
      paths-ignore:
         - "*.md"

jobs:
   build:
      name: Build all the things
      runs-on: ubuntu-18.04
      steps:
         -  uses: actions/checkout@v2
         -  uses: gradle/wrapper-validation-action@v1
         -  uses: actions/cache@v1
            with:
               path: ~/.gradle/caches
               key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
               restore-keys: |
                  ${{ runner.os }}-gradle-
         -  name: Generate Docker image tag
            id: dockertag
            run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"
         -  name: Generate SLSA provenance
            uses: slsa-framework/github-actions-demo@v0.1
            with:
               artifact_path: ./
         -  uses: actions/setup-java@v1
            with:
               java-version: '16.x'
         -  name: Test and build the code
            run: ./gradlew test build
         -  name: Login to GitHub Docker Registry
            uses: docker/login-action@v1
            with:
               registry: ghcr.io
               username: ${{ github.actor }}
               password: ${{ secrets.GITHUB_TOKEN }}
         -  name: Build an push the Docker image
            run: |
               docker build --pull --tag ${{ steps.dockertag.outputs.docker_img }} .
               docker push ${{ steps.dockertag.outputs.docker_img }}

   deploy_to_dev:
      name: Deploy to dev-gcp
      needs: build
      runs-on: ubuntu-18.04
      steps:
         -  uses: actions/checkout@v2
         -  uses: nais/deploy/actions/deploy@v1
            env:
               APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
               CLUSTER: dev-gcp
               RESOURCE: .nais/nais.yaml
               VARS: .nais/dev.yaml
               IMAGE: ${{ steps.dockertag.outputs.docker_img }}
   deploy_to_prod:
      name: Deploy to prod-gcp
      needs: deploy_to_dev
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-18.04
      steps:
         -  uses: actions/checkout@v2
         -  uses: nais/deploy/actions/deploy@v1
            env:
               APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
               CLUSTER: prod-gcp
               RESOURCE: .nais/nais.yaml
               VARS: .nais/prod.yaml
               IMAGE: ${{ steps.dockertag.outputs.docker_img }}
