name: Build and deploy main

on:
   push:
      branches:
         - main
      paths-ignore:
         - "*.md"
         - "build.provenance"
         - "**/cosigntest.yaml"

jobs:
   build:
      name: Build all the things
      runs-on: ubuntu-20.04
      steps:
         -  uses: actions/checkout@v2
         -  name: Run Snyk to check for vulns
            uses: snyk/actions/gradle-jdk17@master
            continue-on-error: true
            env:
               SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            with:
               args: --sarif-file-output=snyk.sarif
         -  name: Upload Snyk result to GitHub Code Scanning
            uses: github/codeql-action/upload-sarif@v1
            with:
               sarif_file: snyk.sarif
         -  name: Generate SLSA provenance
            uses: slsa-framework/github-actions-demo@v0.1
            with:
               artifact_path: ./
         -  name: Upload SLSA provenance
            uses: actions/upload-artifact@v2
            with:
               name: slsa-provenance
               path: build.provenance
         -  uses: actions/setup-java@v2
            with:
               java-version: '17'
               distribution: 'adopt'
               cache: 'gradle'
         -  uses: gradle/wrapper-validation-action@v1
         -  name: Build and test the app
            run: sudo ./gradlew clean test shadowJar
         -  name: Login to GitHub Docker Registry
            uses: docker/login-action@v1
            with:
               registry: ghcr.io
               username: ${{ github.actor }}
               password: ${{ secrets.GITHUB_TOKEN }}
         -  name: Generate Docker image tag with short sha
            id: dockertag
            run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"
         -  name: Build and push the Docker image
            uses: docker/build-push-action@v2
            with:
               context: .
               push: true
               tags: ${{ steps.dockertag.outputs.docker_img }}
               cache-from: type=registry,ref=${{ steps.dockertag.outputs.docker_img }}
               cache-to: type=inline

   deploy_to_dev:
      name: Deploy to dev-gcp
      needs: build
      runs-on: ubuntu-20.04
      steps:
         -  uses: actions/checkout@v2
         -  name: Generate Docker image tag
            id: dockertag
            run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"
         -  uses: nais/deploy/actions/deploy@v1
            env:
               APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
               CLUSTER: dev-gcp
               RESOURCE: .nais/nais.yaml
               VARS: .nais/dev.yaml
               IMAGE: ${{ steps.dockertag.outputs.docker_img }}

   deploy_to_prod:
      name: Deploy to prod-gcp
      needs: deploy_to_dev
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-20.04
      steps:
         -  uses: actions/checkout@v2
         -  name: Generate Docker image tag
            id: dockertag
            run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"
         -  uses: nais/deploy/actions/deploy@v1
            env:
               APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
               CLUSTER: prod-gcp
               RESOURCE: .nais/nais.yaml
               VARS: .nais/prod.yaml
               IMAGE: ${{ steps.dockertag.outputs.docker_img }}
