name: Snyk Container Scan
on:
   push:
      branches:
         - main
jobs:
   build:
      name: Build and push Docker container
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@v2
         -  uses: gradle/wrapper-validation-action@v1
         -  uses: actions/cache@v1
            with:
               path: ~/.gradle/caches
               key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
               restore-keys: |
                  ${{ runner.os }}-gradle-
         -  uses: actions/setup-java@v1
            with:
               java-version: '15.x'
         -  name: test and build
            run: ./gradlew build

   snyk:
      runs-on: ubuntu-latest
      needs: [ build ]
      steps:
         - uses: actions/checkout@v2
         - name: Build a Docker image
           run: docker build -t tulleimage .

         - name: Run Snyk to check Docker image for vulnerabilities
           continue-on-error: true
           uses: snyk/actions/docker@master
           env:
              SNYK_TOKEN: ${{ secrets.SNYK_READ_TOKEN }}
           with:
              image: tulleimage
              args: --file=Dockerfile
         - name: Upload result to GitHub Code Scanning
           uses: github/codeql-action/upload-sarif@v1
           with:
              sarif_file: snyk.sarif
